version: "3.9"
services:

  db:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - PGDATA=/var/lib/postgresql/data/pgdata

  web:
    image: openjdk:11-jre-slim-buster
    working_dir: /app
    command: java -jar db-api.jar
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy        
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  test:
    image: curlimages/curl:7.77.0
    command: curl web:9999/api/cards
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure

