version: '3.7'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
  
  db:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - PGDATA=/var/lib/postgresql/data/pgdata
